### ISSUE TITLE
no more taskbar

### ISSUE THREAD

**Issue by YesTheProxy** [theshmunguss1/RamOS#16]
see title

**Comment by theshmunguss1** [comment]
That was me, I was attempting to fix file paths in `taskbar.html` and it messed up. The files still exist in the `html` folder.

**Comment by DJshelfmushroom** [comment]
I did it

**Comment by theshmunguss1** [comment]
working on it rn

**Comment by theshmunguss1** [comment]
Yes, also the fullscreen iframe is not working. If you go to, say, https://ramnetos.github.io/RamOS/astroidv3.html it loads the favicon, but still gets a 404. If you go to https://ramnetos.github.io/RamOS/html/astroidv3.html it loads the embed but not fullscreen. @DJshelfmushroom, any ideas?

**Comment by theshmunguss1** [comment]
If you look in `taskbar.html`, I'm referencing every HTML file like this: `./html/example.html`.

**Comment by theshmunguss1** [comment]
Wait, it's working now. We just need the iframe CSS to work.

**Comment by theshmunguss1** [comment]
Got everything working, also on `credits.html`. Another issue down...
