### ISSUE TITLE
How do you suppose we can resize this image?

### ISSUE THREAD

**Issue by theshmunguss1** [theshmunguss1/RamOS#2]
https://github.com/theshmunguss1/RamOS/blob/e6457c9fe3722bdc9804c09b84e8152b1320d08a/index.html#L44
@DJshelfmushroom

**Comment by theshmunguss1** [comment]
I've tried like 4 different pieces of code, nothing works

**Comment by DJshelfmushroom** [comment]
do you want it a static size or a percentage of the screen width? what have you tried?

**Comment by DJshelfmushroom** [comment]
because it already auto-resizes as far as I know.

**Comment by DJshelfmushroom** [comment]
also try and do this in the ramos slack channel, that's what it is for.

**Comment by DJshelfmushroom** [comment]
`
#logo {
                display: block;
                // this margin centers it
                margin-left: auto;
                margin-right: auto;
                // and this makes it 85% of the width
                width: 85%;
            }
`

**Comment by theshmunguss1** [comment]
> also try and do this in the ramos slack channel, that's what it is for.

Slack is blocked at my school and I'm not risking taking out my phone.
I've tried code that resizes it via a percentage, via pixel width and height, and nothing works.

**Comment by DJshelfmushroom** [comment]
but doesn't the code already do this?

**Comment by theshmunguss1** [comment]
The code you commented? I'm testing it right now.

**Comment by DJshelfmushroom** [comment]
it's already in index.html

**Comment by theshmunguss1** [comment]
yes, I put it there. It was in the head, it does not work there

**Comment by DJshelfmushroom** [comment]
it does work there. all style goes in the head.

**Comment by DJshelfmushroom** [comment]
oh the image is broken for me.

**Comment by theshmunguss1** [comment]
How so? Mine looks like this
![Screenshot 2024-04-17 1 25 44 PM](https://github.com/theshmunguss1/RamOS/assets/142841882/ef80efcc-6e0e-4059-a59c-28044554c1e6)

**Comment by DJshelfmushroom** [comment]
I fixed it.

**Comment by theshmunguss1** [comment]
I got it thanks
